broadcaster:
  image: anthonykgross/docker-broadcaster
#  environment:
#    YOUTUBE_URL: rtmp://a.rtmp.youtube.com/live2
#    YOUTUBE_STREAMKEY: "NULL"
#    TWITCH_URL: rtmp://live-cdg.twitch.tv/app
#    TWITCH_STREAMKEY: "NULL"
#    HITBOX_URL: rtmp://live.hitbox.tv/push
#    HITBOX_STREAMKEY: "NULL"
#    DAILYMOTION_URL: rtmp://publish.dailymotion.com/publish-dm
#    DAILYMOTION_STREAMKEY: "NULL"
#    YOUR_IP: YOUR_IP
#    PRIVATE_KEY: anthonykgross
#    EXPIRATION_TOKEN: 3600
#    STREAM_SPECIFIER: hd720
#    URL_TRANSCODE: transcode
#    URL_LIVE: live
  ports:
    - 8080:8080
    - 1935:1935
  volumes:
    - ./log:/log
